#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "Please specify a file name"
    exit 1
fi


fileName=$(echo $1 | sed -E "s|^(.*)\.(.*)$|\1|g")
linkerFile="${fileName}.o"

nasm -f elf32 $1 -o ${linkerFile}
ld -m elf_i386 ${linkerFile} -o ${fileName}

./${fileName}
